site_name: Radical Environmental Data
theme:
  name: material
  font:
    text: Lato
  palette:
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate 
      primary: teal
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
  logo: assets/logo-white.svg
  favicon: images/logo-white.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - footnotes
  - md_in_html

plugins:
  - search
  - awesome-pages
  - i18n:
      default_language: en
      languages:
        en:
          name: English
        nl:
          name: Nederlands
          site_name: Radicaal Milieudata
      nav_translations:
        nl:
          Introduction: Introductie
          Course: Cursus

nav:
  - index.md
  - Course:
    - introduction.md
    - finding-open-data.md
    - critiquing-data.md
    - visualising-data.md
    - doing-a-data-walk.md
  - Other:
    - about.md
    - ...

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/radicaldataproject/red

extra_css:
  - stylesheets/extra.css